# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(default='General Enquiry', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
    ]
