# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 14:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20160621_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='enquiry_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.ContactType'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.CharField(max_length=200, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
